[project]
name = "winlator-compare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "javalang",
]

[tool.uv.sources]
javalang = { git = "https://github.com/c2nes/javalang" }
